/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Closet4Doors(props) {
  const { nodes, materials } = useGLTF("assets/3dModels/Closet4Doors.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.back001.geometry}
        material={materials.wood_1}
        position={[0.744, 1.25, -0.902]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.door001.geometry}
        material={materials.wood_1}
        position={[1.344, 1.25, -0.309]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shelf005.geometry}
        material={materials.wood_1}
        position={[0.744, 0.516, -0.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shelf011.geometry}
        material={materials.wood_1}
        position={[0.744, 0.916, -0.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body005.geometry}
        material={materials.wood_1}
        position={[0.744, 1.25, -0.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body006.geometry}
        material={materials.wood_1}
        position={[0.544, 0.1, -0.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body007.geometry}
        material={materials.wood_1}
        position={[2.16, 1.25, -0.899]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body008.geometry}
        material={materials.wood_1}
        position={[0.544, 2.4, -0.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body009.geometry}
        material={materials.wood_1}
        position={[1.544, 1.25, -0.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.door002.geometry}
        material={materials.wood_1}
        position={[0.559, 1.25, -0.309]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.door003.geometry}
        material={materials.wood_1}
        position={[2.157, 1.25, -0.309]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.door004.geometry}
        material={materials.wood_1}
        position={[1.361, 1.25, -0.309]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shelf014.geometry}
        material={materials.wood_1}
        position={[1.544, 0.516, -0.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shelf015.geometry}
        material={materials.wood_1}
        position={[1.544, 0.916, -0.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shelf016.geometry}
        material={materials.wood_1}
        position={[1.544, 1.316, -0.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shelf017.geometry}
        material={materials.wood_1}
        position={[1.544, 1.716, -0.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.chrome}
        position={[0.56, 2.294, -0.605]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sokol002.geometry}
        material={materials.wood_1}
        position={[0.744, 0.05, -0.617]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sokol003.geometry}
        material={materials.wood_1}
        position={[0.744, 0.05, -0.617]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sokol004.geometry}
        material={materials.wood_1}
        position={[0.744, 0.05, -0.617]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sokol005.geometry}
        material={materials.wood_1}
        position={[0.744, 0.05, -0.617]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle_1.geometry}
        material={materials.chrome}
        position={[0.543, 0.9, 0.042]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle_1001.geometry}
        material={materials.chrome}
        position={[0.984, 0.9, -0.293]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle_1002.geometry}
        material={materials.chrome}
        position={[1.721, 0.9, -0.293]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle_1003.geometry}
        material={materials.chrome}
        position={[1.797, 0.9, -0.293]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["ch2-part-1"].geometry}
        material={materials.chrome}
        position={[0.56, 2.222, -0.346]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["ch2-part-1001"].geometry}
        material={materials.chrome}
        position={[0.56, 1.665, -0.346]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["ch2-part-1002"].geometry}
        material={materials.chrome}
        position={[0.56, 1.07, -0.346]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["ch2-part-1003"].geometry}
        material={materials.chrome}
        position={[0.56, 0.297, -0.346]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("assets/3dModels/Closet4Doors.glb");

