/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";

export function Closet4Doors({ width, height, depth, isSokol, material, handleType, RightShelvesNumber, LeftShelvesNumber , isLeftPole, isRightPole, ...props}) {
  const defaultDimensions = [161,230,59]
  const { nodes, materials } = useGLTF("assets/3dModels/Closet4Doors.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.poleLeft.geometry}
        material={materials.chrome}
        position={[-0.763, 2.294, -0.026]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leftPanel.geometry}
        material={materials.wood_1}
        position={[-0.58, 1.25, -0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backPanel.geometry}
        material={materials.wood_1}
        position={[-0.58, 1.25, -0.323]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bottomPanel.geometry}
        material={materials.wood_1}
        position={[-0.78, 0.1, -0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rightPanel.geometry}
        material={materials.wood_1}
        position={[0.837, 1.25, -0.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.topPanel.geometry}
        material={materials.wood_1}
        position={[-0.78, 2.4, -0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.divider.geometry}
        material={materials.wood_1}
        position={[0.221, 1.25, -0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hinge1.geometry}
        material={materials.chrome}
        position={[-0.763, 2.222, 0.233]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hinge2.geometry}
        material={materials.chrome}
        position={[-0.763, 1.665, 0.233]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hinge3.geometry}
        material={materials.chrome}
        position={[-0.763, 1.07, 0.233]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hinge4.geometry}
        material={materials.chrome}
        position={[-0.763, 0.297, 0.233]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.door1.geometry}
        material={materials.wood_1}
        position={[-0.765, 1.25, 0.27]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.door2.geometry}
        material={materials.wood_1}
        position={[0.021, 1.25, 0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.door3.geometry}
        material={materials.wood_1}
        position={[0.037, 1.25, 0.27]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.door4.geometry}
        material={materials.wood_1}
        position={[0.833, 1.25, 0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle1.geometry}
        material={materials.chrome}
        position={[-0.781, 0.9, 0.621]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle2.geometry}
        material={materials.chrome}
        position={[-0.339, 0.9, 0.286]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle3.geometry}
        material={materials.chrome}
        position={[0.397, 0.9, 0.286]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle4.geometry}
        material={materials.chrome}
        position={[0.473, 0.9, 0.286]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.legBackLeft.geometry}
        material={materials["chrome.001"]}
        position={[-0.679, 0.05, -0.273]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.legBackRight.geometry}
        material={materials["chrome.001"]}
        position={[0.758, 0.05, -0.273]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.legFrontLeft.geometry}
        material={materials["chrome.001"]}
        position={[-0.679, 0.05, 0.187]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.legFrontRight.geometry}
        material={materials["chrome.001"]}
        position={[0.758, 0.05, 0.187]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shelfLeft.geometry}
        material={materials.wood_1}
        position={[-0.58, 1.222, -0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shelfRight.geometry}
        material={materials.wood_1}
        position={[0.22, 1.222, -0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sokolBack.geometry}
        material={materials.wood_1}
        position={[-0.58, 0.05, -0.038]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sokolFront.geometry}
        material={materials.wood_1}
        position={[-0.58, 0.05, -0.038]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sokolLeft.geometry}
        material={materials.wood_1}
        position={[-0.58, 0.05, -0.038]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sokolRight.geometry}
        material={materials.wood_1}
        position={[-0.58, 0.05, -0.038]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.poleRight.geometry}
        material={materials.chrome}
        position={[0.037, 2.294, -0.026]}
        rotation={[0, 0, -Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("assets/3dModels/Closet4Doors.glb");

